# Generated by Django 4.0.4 on 2022-07-20 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview_app', '0002_choice_vote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='poll',
            new_name='question',
        ),
    ]
