# Generated by Django 4.0.4 on 2022-07-20 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interview_app', '0003_rename_poll_vote_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=255, verbose_name='Текст ответа')),
            ],
            options={
                'verbose_name': 'Ответы',
                'verbose_name_plural': 'Ответ',
            },
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Опросы', 'verbose_name_plural': 'Опрос'},
        ),
        migrations.AlterModelOptions(
            name='vote',
            options={'verbose_name': 'Выбор', 'verbose_name_plural': 'Выбор'},
        ),
        migrations.RemoveField(
            model_name='vote',
            name='choice',
        ),
        migrations.AlterField(
            model_name='question',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='question',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель опроса'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(verbose_name='Текст опроса'),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview_app.question'),
        ),
        migrations.AddField(
            model_name='vote',
            name='answer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='interview_app.answer'),
            preserve_default=False,
        ),
    ]
