# Generated by Django 4.0.4 on 2022-07-20 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interview_app', '0005_alter_answer_question_alter_question_owner_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chain',
            options={'verbose_name': 'Монеты', 'verbose_name_plural': 'Монеты'},
        ),
        migrations.AlterField(
            model_name='chain',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
