# Generated by Django 4.0.4 on 2022-07-21 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview_app', '0006_alter_chain_options_alter_chain_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chain',
        ),
    ]
