# Generated by Django 4.0.4 on 2022-07-21 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview_app', '0007_delete_chain'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Ответы', 'verbose_name_plural': 'Список ответов'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Тесты', 'verbose_name_plural': 'Список тестов'},
        ),
        migrations.AlterModelOptions(
            name='vote',
            options={'verbose_name': 'Итоги опроса', 'verbose_name_plural': 'Итоги опроса'},
        ),
    ]
