# Generated by Django 4.0.4 on 2022-07-22 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview_app', '0009_remove_answer_question_question_answers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='answers',
            new_name='answer',
        ),
    ]
