# Generated by Django 4.0.4 on 2022-07-21 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='email',
        ),
        migrations.AddField(
            model_name='myuser',
            name='chain',
            field=models.PositiveIntegerField(default=0, verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='login',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='Логин'),
        ),
    ]
