# Generated by Django 4.0.4 on 2022-07-21 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_myuser_count_of_tests'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(default='white', max_length=40)),
                ('color_price', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='myuser',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.usercolor'),
        ),
    ]
