# Generated by Django 4.0.4 on 2022-07-22 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_color_myuser_user_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'verbose_name': 'Пользователя', 'verbose_name_plural': 'Список пользователей'},
        ),
        migrations.AlterModelOptions(
            name='usercolor',
            options={'verbose_name': 'цвет', 'verbose_name_plural': 'Список цветов'},
        ),
        migrations.AddField(
            model_name='usercolor',
            name='color_rus_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='user_color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.usercolor', verbose_name='Цвет'),
        ),
    ]
